version: "2"

services:
  spark-master:
    image: fno2010/spark
    command: master 0.0.0.0
    hostname: spark-master
    container_name: spark-master
    ports:
    - "6066:6066"
    - "7070:7070"
    - "8080:8080"
    - "50070:50070"
  spark-worker:
    image: fno2010/spark
    command: worker spark-master 0.0.0.0
    depends_on:
    - spark-master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
